try:
  print(x)
finally:
  print("The 'try except' is finished")